additional feature
spaceonfire/BMF pull request #3
Opened 2020-10-05 19:16 UTC by xTCry

2020-10-06 15:20 UTC, hustlahusky requested changes
Полезная фича, но есть пару небольших замечаний

2020-10-06 15:20 UTC, hustlahusky commented on src/Options/Form.php
> +								} else if (!empty($opt['fn']) && !is_string($opt['fn']) && is_callable($opt['fn'])) {
Лучше назвать ключ `render`, чтобы было понятно за что он отвечает. Так же достаточно проверить, что ключ установлен и значение можно вызвать как функцию

```suggestion
								} else if (isset($opt['render']) && is_callable($opt['render'])) {
```

2020-10-06 15:20 UTC, hustlahusky commented on src/Options/Form.php
> +									$opt['fn']();
Лучше сделать, чтобы функция генерировала html для вывода

```suggestion
									echo $opt['render']();
```

2020-10-06 19:47 UTC, xTCry commented on src/Options/Form.php
> +								} else if (!empty($opt['fn']) && !is_string($opt['fn']) && is_callable($opt['fn'])) {
Подразумевалось, что в _fn_ будет передана исключительно функция, а не строковой адрес на нее

2020-10-06 19:47 UTC, xTCry commented on src/Options/Form.php
> +									$opt['fn']();
Можно, но вывод может быть необязательным, что, конечно, маловероятно

И если функция будет выводить какой-то сложный контент, тогда придется использовать _ob_get_clean_
Поэтому, думаю, лучше просто оставить её вызов без _echo_

2020-10-06 23:14 UTC, xTCry commented on src/Options/Form.php
> +								} else if (!empty($opt['fn']) && !is_string($opt['fn']) && is_callable($opt['fn'])) {
Например
```php
$COMPOSER_MODULE->options->addOption('COMPOSER_HTML', [
	'tab' => 'default',
	'type' => 'html',
	'fn' => function() {
		global $COMPOSER_PATH, $COMPOSER_PATH_default;
		// Получить обновленное значение после сохранения
		$COMPOSER_PATH = Option::get(ADMIN_MODULE_NAME, 'COMPOSER_PATH', $COMPOSER_PATH_default);
		echo ComposerUI::instance()->render();
	}
]);
```

2020-10-07 06:29 UTC, hustlahusky commented on src/Options/Form.php
> +								} else if (!empty($opt['fn']) && !is_string($opt['fn']) && is_callable($opt['fn'])) {
Это не так важно в каком формате будет передана функция. Главное чтобы это действительно была функция и ее можно было вызвать. Это может быть и Closure, как в твоем случае, так и строка с именнем функции, так метод класса/объекта в формате массива. Подробнее тут, [что php считает callable](https://www.php.net/manual/ru/language.types.callable.php)

2020-10-07 06:43 UTC, xTCry commented
+

2020-10-07 06:44 UTC, hustlahusky commented on src/Options/Form.php
> +									$opt['fn']();
Вывод из самой функции напрямую - это скорее сайд-эффект, чем ожидаемое поведение. Если сделать вывод возвращаемого значения через echo, для пользователя библиотеки API этой фичи будет удобнее. Внутри этой функции он сможет реализовать рендеринг, как ему будет угодно. Хоть рендерингом какого-нибудь своего шаблона, хоть сгенерирует HTML с помощью других утилит (типа nette/utils), хоть сам завернет свой вывод напрямую в буфферизацию.

В дальнейшем я планирую переделать архитектуру библиотеки. Разделить рендеринг самой формы настроек от кода, добавить нужные абстрации для описания настроек и пр. Поэтому для данной фичи так же необходимо определить четкое API, которое поможет в сохранении обратной совместимости и тестировании

2020-10-07 06:47 UTC, xTCry commented on src/Options/Form.php
> +									$opt['fn']();
Прошло больше года, а обновлений так и не было
Хотя в планах, да, это есть

2020-10-07 06:51 UTC, hustlahusky commented on src/Options/Form.php
> +									$opt['fn']();
Не так много свободного времени. На все что хотелось бы сделать не хватает

2020-10-22 21:44 UTC, xTCry commented on src/Options/Form.php
> +									$opt['fn']();
Код, который изменили в этом комментарии, не может быть применен к этому PR?

2020-10-22 21:46 UTC, xTCry commented
Добавил новый коммит xTCry@7022cb5fc8767a3690f700406f33af8e3a996e96

2020-10-23 14:26 UTC, hustlahusky approved these changes

2020-10-23 14:29 UTC, merged

2020-10-23 14:33 UTC, hustlahusky commented
@xTCry, спасибо за PR. Выпустил версию 1.1.0 с этими изменениями.